#!/usr/bin/env bash
#
# Regenerate docs/workflows/<name>.md for every reusable (workflow_call)
# workflow in .github/workflows/, via actdocs (github.com/tmknom/actdocs).
#
# self-*.yml is skipped: those call this repo's own workflows through a
# local `uses: ./...` path and are internal plumbing, not part of the
# public catalogue (see AGENTS.md, "What this repo is NOT"). Anything
# without a `workflow_call:` trigger -- fleet-internal schedule/workflow_run
# automation like fleet-mirror.yml -- is skipped too.
#
# docs/workflows/ is wiped and rebuilt from scratch each run, so a workflow
# that gets deleted or renamed doesn't leave a stale doc behind -- the exact
# class of drift README.md had for dependabot-auto-approve.yml (deleted in
# #54, still documented until #80).

set -euo pipefail

ACTDOCS_IMAGE="ghcr.io/tmknom/actdocs:v0.6.1"
WORKFLOW_DIR=".github/workflows"
OUT_DIR="docs/workflows"

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

for workflow in "${WORKFLOW_DIR}"/*.yml; do
  name="$(basename "${workflow}" .yml)"

  case "${name}" in
    self-*) continue ;;
  esac

  if ! grep -qE '^\s*workflow_call:\s*$' "${workflow}"; then
    continue
  fi

  out_file="${OUT_DIR}/${name}.md"
  {
    echo "<!-- Generated by actdocs from ${workflow}. Do not edit by hand -- run"
    echo "     .pre-commit-scripts/generate-workflow-docs.sh to regenerate. -->"
    echo
    echo "# \`${name}.yml\`"
    echo
    # --sort-by-name: actdocs otherwise emits rows in Go map iteration order,
    # which is randomized per run and makes every regeneration diff noisy
    # regardless of whether the workflow actually changed.
    docker run --rm -v "$(pwd):/work" -w /work "${ACTDOCS_IMAGE}" generate --omit --sort-by-name "${workflow}"
  } >"${out_file}"
done
